global:
  resolve_timeout: 5m
  # Default SMTP configuration (uncomment and configure as needed)
  # smtp_smarthost: 'smtp.example.com:587'
  # smtp_from: 'alerts@example.com'
  # smtp_auth_username: 'username'
  # smtp_auth_password: 'password'

# Email templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# The root route on which each incoming alert enters
route:
  # Default receiver
  receiver: 'team-general'
  
  # How long to wait before sending a notification again
  repeat_interval: 4h
  
  # How long to wait to buffer alerts of the same group
  group_wait: 30s
  
  # How long to wait before sending a notification about new alerts that are in a group
  group_interval: 5m
  
  # Split alerts into groups based on labels
  group_by: ['alertname', 'component']
  
  # Child routes
  routes:
    - match:
        severity: critical
      receiver: 'team-critical'
      repeat_interval: 1h
    
    - match:
        severity: warning
      receiver: 'team-warnings'
      repeat_interval: 12h

# Receivers define notification integrations
receivers:
  - name: 'team-general'
    # Webhook configuration (example)
    webhook_configs:
      - url: 'http://127.0.0.1:5001/alert'
        send_resolved: true
    
    # Email configuration (example)
    # email_configs:
    #   - to: 'team@example.com'
    #     send_resolved: true
  
  - name: 'team-critical'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/alert/critical'
        send_resolved: true
    # email_configs:
    #   - to: 'oncall@example.com'
    #     send_resolved: true
  
  - name: 'team-warnings'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/alert/warning'
        send_resolved: true

# Inhibition rules allow suppressing notifications for less severe alerts
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    # Apply inhibition if the alertname and component are the same
    equal: ['alertname', 'component']